;             
CREATE USER IF NOT EXISTS "SA" SALT '076a05df30895902' HASH 'a566fd623f1b0b64dc4c4b973610226c510e70bc268208b6f8fcd0baa573339a' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ1" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ2" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ3" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ4" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ5" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ6" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ7" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ8" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ9" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQ10" START WITH 1 BELONGS_TO_TABLE;


CREATE MEMORY TABLE "PUBLIC"."BADDY"(
    "TIME" TIMESTAMP,
    "NAME" VARCHAR(6)
);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BADDY;   
CREATE TABLE "PUBLIC"."DASHBOARD_HISTORY"(
    "DASHBOARD_HISTORY_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ4",
    "ID" BIGINT NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DEFAULT_PARAMS" VARCHAR(255) NOT NULL,
    "DATE_CREATED" TIMESTAMP NOT NULL,
    "DATE_UPDATED" TIMESTAMP NOT NULL,
    "DATA" CLOB
);
ALTER TABLE "PUBLIC"."DASHBOARD_HISTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("DASHBOARD_HISTORY_ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DASHBOARD_HISTORY;       
CREATE TABLE "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ3" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ3",
    "NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255),
    "DATE_CREATED" TIMESTAMP,
    "DATE_UPDATED" TIMESTAMP,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "ADMIN" BOOLEAN NOT NULL,
    "DELETED" BOOLEAN NOT NULL
);         
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         



CREATE TABLE "PUBLIC"."DASHBOARD"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ1",
    "VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DEFAULT_PARAMS" VARCHAR(2000) NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_UPDATED" TIMESTAMP,
    "DATA" CLOB
);      
ALTER TABLE "PUBLIC"."DASHBOARD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DASHBOARD;               
CREATE TABLE "PUBLIC"."REPORT_CONFIG"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ9" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ9",
    "VERSION" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_UPDATED" TIMESTAMP,
    "URL" VARCHAR(255) NOT NULL,
    "CRON" VARCHAR(255) NOT NULL,
    "WIDTH" INT,
    "HEIGHT" INT,
    "SECONDS_DELAY" INT,
    "OWNER_ID" BIGINT NOT NULL,
    "DASH_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REPORT_CONFIG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REPORT_CONFIG;           
CREATE TABLE "PUBLIC"."REPORT_RESULT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ7" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ7",
    "VERSION" BIGINT NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "DATE_UPDATED" TIMESTAMP,
    "URL" VARCHAR(255) NOT NULL,
    "REPORT_ID" BIGINT NOT NULL,
    "DASH_ID" BIGINT NOT NULL,
    "DATE_COMPLETED" TIMESTAMP,
    "RESULT" VARCHAR(255) NOT NULL,
    "LOG" TEXT,
    "HTML" TEXT,
    "SUCCEEDED" BOOLEAN NOT NULL,
    "IMG" BLOB
);    
ALTER TABLE "PUBLIC"."REPORT_RESULT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_28" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REPORT_RESULT;           
CREATE TABLE "PUBLIC"."DATASOURCE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ6",
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "DATABASE" VARCHAR(255) NOT NULL,
    "URL" VARCHAR(255) NOT NULL,
    "KDB" BOOLEAN NOT NULL,
    "STREAMING" BOOLEAN NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "HOST" VARCHAR(255) NOT NULL,
    "PORT" INT NOT NULL,
    "JDBC_TYPE" INT NOT NULL
);
ALTER TABLE "PUBLIC"."DATASOURCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9F" PRIMARY KEY("ID");  



CREATE TABLE "PUBLIC"."PAGE_VIEW"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ2" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ2",
    "URL" VARCHAR(500) NOT NULL,
    "PATH" VARCHAR(255) NOT NULL,
    "SEARCH" VARCHAR(500) NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "ANONYMOUS_ID" VARCHAR(255) NOT NULL,
    "DASH_ID" BIGINT NOT NULL,
    "DASH_NAME" VARCHAR(255) NOT NULL,
    "USER_ID" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."PAGE_VIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PAGE_VIEW;               

CREATE TABLE "PUBLIC"."DASHBOARD_SCREENSHOT"(
    "DASHBOARD_SCREENSHOT_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ10" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ10",
    "ID" BIGINT NOT NULL,
    "SCREENSHOT" BLOB
);    
ALTER TABLE "PUBLIC"."DASHBOARD_SCREENSHOT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("DASHBOARD_SCREENSHOT_ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DASHBOARD_SCREENSHOT;    
CREATE TABLE "PUBLIC"."SUBSCRIPTION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ8" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ8",
    "USER_ID" BIGINT NOT NULL,
    "REPORT_ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."SUBSCRIPTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUBSCRIPTION;            
CREATE TABLE "PUBLIC"."EVENT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQ5" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQ5",
    "EVENT" VARCHAR(255) NOT NULL,
    "DATE_CREATED" TIMESTAMP,
    "ANONYMOUS_ID" VARCHAR(255) NOT NULL,
    "DASH_ID" BIGINT NOT NULL,
    "DASH_NAME" VARCHAR(255) NOT NULL,
    "USER_ID" VARCHAR(255)
);        
ALTER TABLE "PUBLIC"."EVENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT;   
