ALTER TABLE "PUBLIC"."DATASOURCE" ADD QUERY_WRAP_PRE VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE "PUBLIC"."DATASOURCE" ADD "WRAP_QUERY" BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE "PUBLIC"."DATASOURCE" ADD QUERY_WRAP_POST VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE "PUBLIC"."DATASOURCE" DROP COLUMN URL;
ALTER TABLE "PUBLIC"."DATASOURCE" DROP COLUMN KDB;
ALTER TABLE "PUBLIC"."DATASOURCE" DROP COLUMN STREAMING;

